### ISSUE TITLE
Can't connect to Redis on Heroku [renamed]

### ISSUE THREAD

**Issue by harlantwood** [Colu-platform/colu-nodejs#1]
I get a connection error when Colu can't find redis.  On localhost this is easy to fix by starting `redis-server`.  On heroku it's not so easy -- for a heroku redis addon, there is a username and password for the redis instance, as well as the `redisHost` and `redisPort` variables used by the [Colu constructor](https://github.com/Colu-platform/colu-nodejs#constructor).

I tried passing `username:password@host` into the host, but that didn't work.

What is Redis used for anyway?  Should I care or just ignore these warnings?  If we should care, then it would be nice to support heroku-style env variables out of the box, which look something like

`redis://username:password@host:port/`

or at minimum provide a way to pass the username/password to the constructor.

**Comment by harlantwood** [comment]
cc @fractastical @dukedorje

**Comment by dukedorje** [comment]
i understood it as a caching layer that hides the ~10 minute bitcoin transaction verification ... could be wrong though

**Comment by thehobbit85** [comment]
@dukedorje  You are mistaken.
Redis is used in to cache your used derived private keys (the one derived and managed by the hdwallet module).
If Redis is not available it will try and cache the data on the filesystem or even on Local-Storage if you are running it from the browser.

If no caching is found it means that every time you restart the SDK you need to go through a "discovery" process and derive again all your used keys which can take some time without caching when usage gets larger.

**Comment by dukedorje** [comment]
I implemented code to parse the heroku connection URL.  However, our app will not work until we are able to pass auth info as well as server/port into the Colu Redis connection.

**Comment by dukedorje** [comment]
Or if we can disabled Redis. Currently throwing an error if it can't connect.

**Comment by dukedorje** [comment]
If we could only pass in the redisUrl in the settings, have colu.js pass it to dataStorage.js, and then use it to connect to redis.
```
redis.createClient('redis://user:pass@host:port', options)
```

Or just fall back to FileSystem properly.

**Comment by harlantwood** [comment]
fixed in #5

**Comment by thehobbit85** [comment]
I merged the fix in.
