### ISSUE TITLE
Importing external keys

### ISSUE THREAD

**Issue by jvgelder** [Colu-platform/colu-nodejs#13]
For paper wallets I needed functionality to import/sign with external keys. I did not see any options in either colu-nodejs nor hdwallet, so I created a ugly hack:
https://github.com/jvgelder/colu-nodejs/commit/9bf1b4a866fe5841222d7e73b82c00cf4d064758

The way I use that hack is as follows (node express):
```javascript
var data = {
    from: [fromAddress],
    to: [{
        address: toAddress,
        assetId: assetID,
        ......
    }]
}
var keypair = bitcoin.ECKey.fromWIF(mywif)
colu.sendAssetWithPriv(send, keypair, function (err, body){
    if (err) return res.status(400).send(err)
    res.status(200).send(body)
})
```
The keypair is a self selected key from an external source.

It would be nice to properly implement importing external keys.

**Comment by tal-beja** [comment]
As for now, the colu-sdk works only with one seed and it is stateless (the redis is for caching purposes only).
So there is no where to save the external imported keys.
